name: Build and Push Docker image (Main)

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t utkarsh1905/doc2pdf-storage:${{ env.VERSION }} .
          docker tag utkarsh1905/doc2pdf-storage:${{ env.VERSION }} utkarsh1905/doc2pdf-storage:latest

      - name: Push Docker image
        run: |
          docker push utkarsh1905/doc2pdf-storage:${{ env.VERSION }}
          docker push utkarsh1905/doc2pdf-storage:latest
